### ISSUE TITLE
wget on develop seems broken

### ISSUE THREAD

**Issue by Stibbons** [hotio/docker-sonarr#1]
When using VERSION, the wget on ```http://download.sonarr.tv/v2/$\{BRANCH\}/mono/Sonarr.$\{BRANCH\}.$\{VERSION\}.mono.tar.gz``` seems broken

I recommend using ```https://github.com/Sonarr/Sonarr/releases``` to download develop version.

PS: you docker-radarr works great ! Thanks for these easily updatable docker !

**Comment by hotio** [comment]
How are you setting the variables, which values?
```
-e BRANCH=develop
-e VERSION=2.0.0.4578
```

Why would you recommend `https://github.com/Sonarr/Sonarr/releases`? Call me stupid, but I don't seem to see any compiled binaries there.

**Comment by Stibbons** [comment]
Ho, it works with this version: 2.0.0.4578

It's me the stupid, I was trying to set up the version v2.0.0.4645 which indeed is not available in binary. Maybe you can add the URL http://download.sonarr.tv/v2/develop/mono/ in the README for user to find the latest binaries?

I close this ticket
